const devotions=[
['Ikuti Injil yang Orisinal','Iman Kristen tidak dibangun di atas apa yang sedang populer, melainkan pada kabar baik tentang Yesus Kristus. Setiap hari kita berhadapan dengan banyak suara: pendapat orang, tren media sosial, kekhawatiran, ambisi, bahkan suara hati yang kadang berubah-ubah. Karena itu kita perlu kembali kepada Injil dan membiarkan firman Tuhan membentuk cara kita berpikir, berbicara, mengambil keputusan, dan memperlakukan sesama. Mengikuti Injil yang benar bukan hanya mengetahui ayat, tetapi memberi ruang bagi Kristus untuk menjadi pusat kehidupan. Ketika gereja berpegang pada Injil, pelayanan tidak kehilangan arah; ketika keluarga berpegang pada Injil, kasih dan pengampunan mendapat dasar; ketika setiap jemaat berpegang pada Injil, kita belajar hidup dalam kebenaran sekaligus kasih. Hari ini, tanyakan kepada diri sendiri: suara apa yang paling banyak memengaruhi keputusan saya? Bawalah pertanyaan itu dalam doa dan mintalah Tuhan menolong kita kembali kepada Kristus.','Galatia 1:6–10'],
['Tuhan Menyertai Langkahmu','Ada hari ketika kita merasa kuat dan ada hari ketika langkah terasa berat. Namun penyertaan Tuhan tidak bergantung pada perasaan kita. Tuhan hadir ketika kita bekerja, belajar, melayani, menjaga keluarga, menghadapi masalah, maupun ketika kita hanya mampu berdoa dalam keheningan. Penyertaan-Nya mengajar kita untuk tidak menyerah pada ketakutan. Kita tetap boleh berhati-hati dan merencanakan dengan baik, tetapi kita tidak perlu hidup dikuasai kecemasan. Hari ini lakukan bagian yang Tuhan percayakan dengan setia. Selesaikan satu tanggung jawab, hubungi seseorang yang membutuhkan penguatan, dan serahkan hal-hal yang berada di luar kendali kita kepada-Nya.','Yosua 1:9'],
['Bersyukur dalam Proses','Syukur bukan berarti kita menutup mata terhadap kesulitan. Syukur berarti kita belajar melihat bahwa di tengah proses yang belum selesai, Tuhan tetap bekerja. Ada jawaban doa yang datang cepat, ada yang membutuhkan waktu, dan ada pula yang baru kita pahami setelah melewati perjalanan panjang. Dalam semua itu, hati yang bersyukur menjaga kita dari keputusasaan. Cobalah mengingat kembali pertolongan Tuhan yang pernah kita alami. Mungkin sederhana: kesehatan, keluarga, sahabat, kesempatan melayani, makanan hari ini, atau kekuatan untuk bangun dan menjalani hari. Sebutkan semuanya satu per satu dalam doa. Syukur mengubah cara kita melihat hidup: bukan karena semua keadaan sudah sempurna, tetapi karena kita tahu kepada siapa kita bersandar.','1 Tesalonika 5:18'],
['Kuat dalam Pengharapan','Pengharapan Kristen bukan sekadar optimisme bahwa semuanya akan berjalan sesuai keinginan kita. Pengharapan adalah keyakinan bahwa Tuhan tetap memegang hidup kita, bahkan ketika kita belum melihat jalan keluar. Karena itu, saat jawaban doa belum terlihat, jangan buru-buru menyimpulkan bahwa Tuhan diam. Ada pekerjaan Tuhan yang berlangsung di dalam hati, karakter, relasi, dan proses yang tidak langsung tampak. Tetaplah berdoa, tetaplah membaca firman, tetaplah melakukan kebaikan, dan tetaplah berjalan bersama komunitas iman. Pengharapan membuat kita mampu menunggu tanpa kehilangan arah. Hari ini serahkan satu pergumulan terbesar kepada Tuhan dan mintalah kekuatan untuk setia menjalani langkah berikutnya.','Roma 12:12'],
['Melayani dengan Kasih','Pelayanan gereja bukan perlombaan untuk terlihat paling aktif. Pelayanan adalah respons syukur karena kita telah menerima kasih Kristus. Karena itu kualitas hati penting: apakah kita melayani dengan kasih, kerendahan hati, kesediaan mendengar, dan kemauan bekerja sama? Dalam gereja, ada pelayanan yang terlihat di depan dan ada yang berlangsung diam-diam. Keduanya berharga di hadapan Tuhan. Mari kita belajar menghargai setiap orang yang mengambil bagian, dari mereka yang menyiapkan ibadah sampai mereka yang membersihkan ruangan, mendampingi anak, mengunjungi yang sakit, menyambut jemaat, atau mendoakan pelayanan. Hari ini pilih satu tindakan sederhana yang membuat orang lain merasakan kasih Kristus.','Galatia 5:13'],
['Damai di Tengah Kekhawatiran','Kekhawatiran sering membuat pikiran berlari jauh sebelum masalah benar-benar terjadi. Firman Tuhan mengajar kita untuk membawa segala sesuatu dalam doa. Doa tidak selalu langsung mengubah situasi, tetapi doa mengarahkan kembali hati kepada Tuhan. Ketika kita berdoa, kita mengakui bahwa kemampuan kita terbatas dan bahwa hidup tidak harus kita kendalikan seorang diri. Tuliskan apa yang sedang mengganggu pikiran Anda. Setelah itu, ubahlah setiap kekhawatiran menjadi kalimat doa. Mintalah hikmat untuk bagian yang harus Anda kerjakan, keberanian untuk bagian yang harus Anda hadapi, dan penyerahan untuk bagian yang tidak dapat Anda kendalikan. Biarlah damai Kristus menjaga hati dan pikiran kita hari ini.','Filipi 4:6–7'],
['Menjadi Berkat di Mana Pun','Kesaksian tidak selalu dimulai dari mimbar. Sering kali kesaksian dimulai dari rumah, tempat kerja, sekolah, lingkungan, dan percakapan sederhana. Ketika kita memilih jujur, mengampuni, menolong, menghormati, dan berbicara dengan kasih, orang lain dapat melihat sesuatu tentang Kristus melalui kehidupan kita. Gereja yang missioner bukan hanya gereja yang memiliki banyak kegiatan, tetapi gereja yang mengutus jemaat membawa kasih Tuhan ke tengah dunia. Hari ini jangan menunggu kesempatan besar. Jadilah berkat melalui tindakan kecil yang nyata. Sebuah pesan penguatan, pertolongan kepada tetangga, kesediaan mendengar, atau pengampunan dapat menjadi kesaksian yang kuat.','Matius 5:16']
];
const d=new Date();const start=new Date(2026,0,1);const idx=Math.floor((new Date(d.getFullYear(),d.getMonth(),d.getDate())-start)/86400000)%devotions.length;const v=devotions[(idx+devotions.length)%devotions.length];
const date=d.toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'});for(const id of ['devDate','fullDevDate'])document.getElementById(id).textContent=date;document.getElementById('devTitle').textContent=v[0];document.getElementById('devText').textContent=v[1];document.getElementById('devRef').textContent=v[2];document.getElementById('fullDevTitle').textContent=v[0];document.getElementById('fullDevText').textContent=v[1];document.getElementById('fullDevRef').textContent=v[2];document.getElementById('year').textContent=d.getFullYear();
document.querySelector('.menu-btn')?.addEventListener('click',()=>document.querySelector('.navlinks').classList.toggle('open'));
